name: my-first-workflow
# To get a trigger on every push 
on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
      
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          
      - name: Step-2
        uses: actions/checkout@v5.0.0
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt
          mkdir artifacts
          echo `ls -ltr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
      - name: Upload single file
        uses: actions/upload-artifact@v5.0.0
        with:
          name: single_file
          path: ./myartifact.txt
  job2:
    name: Job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking current directory
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: single_file
      - name: Checking current directory post download
        run: |
          pwd
          ls -ltr
      - name: Refering repo secret
        run: |
          echo "[Info ] app password is ${{ secrets.APP_PASSWORD }} "
  job3:
    name: Job3
    runs-on: ubuntu-latest
    steps:
      - name: Referring context or in-built variables.
        run: |
          echo "[INFO] Triggered by ${{ github.event_name }}"
          echo "[INFO] New changes were added by ${{ github.actor }} in ${{ github.ref_name }} branch. "
          echo "[INFO] Current step is running on ${{ runner.os }}. "
          echo "[INFO] Current Job Id is ${{ job.check_run_id }}. "
staging:
  name: Stage Deployment
  runs-on: ubuntu-latest
  steps: 
    - name: Referring Environment Variables
      run: echo "[INFO] Running deployment on s ${{ vars.Host }} using ${{ vars.User }}. "
    - name: Referring Environment Secrets
      run: echo "[INFO] Password for ${{ vars.User }} is ${{ secrets.PASSWORD }}. "
  environment:
    - name: STAGING
production:
  name: Production Deployment
  runs-on: ubuntu-latest
  steps: 
    - name: Referring Environment Variables
      run: echo "[INFO] Running deployment on s ${{ vars.Host }} using ${{ vars.User }}. "
    - name: Referring Environment Secrets
      run: echo "[INFO] Password for ${{ vars.User }} is ${{ secrets.PASSWORD }}. "
  environment:
    - name: PRODUCTION
       
      
      - name: Stop for PR demo
        run: exit 0
