name: my-first-workflow

# To get a trigger on every push
on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main
      - dev

jobs: 
  unit-tests:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v5

     - name: Referring context or in-built variables.
       run: |
         echo "[INFO] Triggered by ${{ github.event_name }}"
         echo "[INFO] New changes were added by ${{ github.actor }} in ${{ github.ref_name }} branch. "
         echo "[INFO] Current step is running on ${{ runner.os }}. "
         echo "[INFO] Current Job Id is ${{ job.check_run_id }}. "

  staging:
    name: Stage Deployment
    runs-on: ubuntu-latest
   
    steps: 
      - name: Referring Environment Variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }} using ${{ vars.USER }}. "
      - name: Referring Environment Secrets
        run: echo "[INFO] Password config loaded." # Avoid echoing raw secrets
    environment: 
      name: Staging  # Corrected syntax
    if: github.ref == 'refs/heads/dev'
  production:
    name: Production Deployment
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write # Required to upload the results of the CodeQL analysis
    strategy:
      matrix:
        language: [python]
      fail-fast: false
    steps:
      - name: Referring Environment Variables
        run: echo "[INFO] Running deployment on ${{ vars.HOST }}  using ${{ vars.USER }}. "
      - name: Referring Environment Secrets
        run: echo "[INFO] Password config loaded."
    environment:
      name: Production  # Corrected syntax
    if: github.ref == 'refs/heads/main'
